/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainWorkflowsIndexRouteImport } from './routes/(main)/workflows/index'
import { Route as mainWorkflowsWorkflowIdIndexRouteImport } from './routes/(main)/workflows/$workflowId/index'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainWorkflowsIndexRoute = mainWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainWorkflowsWorkflowIdIndexRoute =
  mainWorkflowsWorkflowIdIndexRouteImport.update({
    id: '/workflows/$workflowId/',
    path: '/workflows/$workflowId/',
    getParentRoute: () => mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workflows': typeof mainWorkflowsIndexRoute
  '/workflows/$workflowId': typeof mainWorkflowsWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workflows': typeof mainWorkflowsIndexRoute
  '/workflows/$workflowId': typeof mainWorkflowsWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/workflows/': typeof mainWorkflowsIndexRoute
  '/(main)/workflows/$workflowId/': typeof mainWorkflowsWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workflows' | '/workflows/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workflows' | '/workflows/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(main)/workflows/'
    | '/(main)/workflows/$workflowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/workflows/': {
      id: '/(main)/workflows/'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof mainWorkflowsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/workflows/$workflowId/': {
      id: '/(main)/workflows/$workflowId/'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof mainWorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainWorkflowsIndexRoute: typeof mainWorkflowsIndexRoute
  mainWorkflowsWorkflowIdIndexRoute: typeof mainWorkflowsWorkflowIdIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainWorkflowsIndexRoute: mainWorkflowsIndexRoute,
  mainWorkflowsWorkflowIdIndexRoute: mainWorkflowsWorkflowIdIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
